# fly.toml app configuration file generated for nextjs-basic-autumn-sunset-4816 on 2024-12-19T18:52:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nextjs-basic-autumn-sunset-4816'


[env]
  LOG_LEVEL = "debug"
  ENHANCE_IMAGE = "true"
  S3_BUCKET = "my-app-production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
